db:
  user: 'ia637'
  pw: 'ia637.Clarkson'
  host: 'mysql.clarksonmsda.org'
  db: 'ia637_Marketplace'
poll_user: 'esuyawkal'
tables:
  user: 'users'
  product: 'products'
  order: 'orders'
  image: 'images'
  message: 'messages'
  favorite: 'favorites'
